@startuml
' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity " teacher " as teacher {
    id: /bigint(20)
    teacher_name: /varchar(255)
    age: /int(11)
    sex: /int(11)
}

entity " student " as student {
    id: /bigint(20) unsigned
    student_name: /varchar(255)
    student_code: /varchar(255)
    sex: /varchar(255)
    age: /int(11)
    class_id: 班级ID/bigint(20)
}

entity " class_teacher " as class_teacher {
    id: /bigint(20)
    class_id: /bigint(20)
    teacher_id: /bigint(20)
}

entity " class " as class {
    id: /bigint(11)
    manager: /varchar(255)
    student_count: /int(11)
    grade_num: 年级/int(11)
    class_num: 班级/int(11)
}



teacher ||--o{ class_teacher
class ||--o{ class_teacher


@enduml