@startuml
' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity " real_room_source 房东-房源表" as real_room_source {
    id: 出租房源表id/bigint(20) unsigned
    landlord_account_id: 房东账号id/bigint(20)
    landlord_room_source_id: 房源表主表id/bigint(20)
    room_status: 房屋状态/tinyint(4)
    rent_start_time: 出租开始时间/date
    rent_end_time: 出租结束时间/date
    room_form_type: 房屋类型，主卧，次卧，客厅，阳台,一居室,两居室,开间/int(11)
    room_index: 房屋编号/varchar(30)
    room_desc: 房屋出租描述/varchar(500)
    room_price: 出租价格/月/decimal(10,0)
    room_rent_form: 出租形式(整租,合租)/int(11)
    room_pay_form: 租金形式(月付,季度付,半年付,整年付)/int(11)
    service_price: 服务费（中介房源，与押金类似）/decimal(10,0)
}

entity " room_landlord 房东表" as room_landlord {
    id: 房东id，主键id/bigint(20) unsigned
    chinese_name: 房东姓名/varchar(50)
    card_number: 房东身份证号/varchar(50)
    card_number_urls: 房东人身份证图片(正反面)/varchar(200)
    handphone: 房东电话/varchar(20)
    check_status: 审核状态/tinyint(4)
}

entity " room_publish 代理人-房源发布表" as room_publish {
    id: 代理人id，主键id/bigint(20) unsigned
    publisher_account_id: 发布人账号id/bigint(20)
    room_source_id: 真实房源id/bigint(20)
    publish_source_id: 发布的房源id/bigint(20)
    create_time: 记录创建时间/发布时间/timestamp
}

entity " landlord_contract_template 房东合同模板表" as landlord_contract_template {
    id: 房源表id/bigint(20) unsigned
    landlord_account_id: 房东账号id/bigint(20)
    contract_template_id: 合同模板id/bigint(20)
    create_time: 记录创建时间/timestamp
}

entity " landlord_room_source 房东-房源表" as landlord_room_source {
    id: 房源表id/bigint(20) unsigned
    landlord_account_id: 房东账号id/bigint(20)
    area_id: 房源所属行政区域id/int(11)
    area_code: 房源所属小区/varchar(50)
    floor_address: 房源所在楼层单元地址/varchar(200)
    handphone: 房东电话/varchar(20)
    create_time: 账号创建时间/timestamp
    room_form_type: 户型类型/tinyint(4)
    source_numbers: 可出租房间数量/tinyint(4)
    size_info: 房屋面积/decimal(10,0)
    living_room_num: 客厅数目/int(11)
    kitchen_num: 厨房数目/int(11)
    toilet_num: 卫生间数目/int(11)
    require_info: 出租要求/varchar(5000)
    decorate_info: 装修情况，精装修，简装修，毛坯房/int(11)
    support_equipments: 支持的房屋设备/varchar(100)
    money_water: 水费/吨/decimal(10,0)
    money_thunder: 电费/度/decimal(10,0)
    money_internet: 网费/月/decimal(10,0)
    money_manage: 物业费/月/decimal(10,0)
    money_car_park: 停车费/月/decimal(10,0)
}

entity " attract_investment 招商服务注册表" as attract_investment {
    id: 主键id/bigint(20) unsigned
    chinese_name: 招商对象名称/varchar(100)
    handphone: 联系电话/varchar(20)
    investment_type: 招商类型/tinyint(4)
    company_address: 公司地址/varchar(200)
    start_time: 合作开始时间/date
    end_time: 合作结束时间/date
    is_openaccount: 是否开通账号/tinyint(4)
    account_id: 会员账号id/bigint(20)
    create_time: 记录创建时间/timestamp
}

entity " room_agent 代理人表" as room_agent {
    id: 代理人id，主键id/bigint(20) unsigned
    chinese_name: 代理人姓名/varchar(50)
    card_number: 代理人身份证号/varchar(50)
    card_number_urls: 代理人身份证图片(正反面)/varchar(200)
    handphone: 代理人电话/varchar(20)
    area_codes: 代理小区列表/varchar(500)
}

entity " room_subscribe 代理人-预约看房记录表" as room_subscribe {
    id: 主键id/bigint(20) unsigned
    agent_account_id: 代理人账号id/bigint(20) unsigned
    room_agent_type: 代理人类型0:房东,1:代理人,2:中介/tinyint(4) unsigned
    user_id: 用户id/bigint(11) unsigned
    area_code: 房源所属小区/看房小区/varchar(50)
    floor_address: 房源所在楼层单元地址/varchar(200)
    mind_hourse_before: 提前N小时提醒/int(11)
    handphone: 用户电话/varchar(20)
    is_mind: 是否进行预约提醒/int(11)
    subscribe_time: 预约时间/date
    subscribe_result: 看房结果/varchar(500)
}

entity " account 合作用户表" as account {
    id: 账号id/bigint(20) unsigned
    nick_name: 账号昵称/varchar(100)
    pass_word: 密码/varchar(100)
    account_type: 账号类型（代理人，房东，招商用户）/tinyint(4)
    member_id: 代理人，房东，招商用户id /bigint(20)
    status: 账号状态/tinyint(4)
    handphone: 电话号码/varchar(100)
}

entity " room_agent_order 代理人-签单表" as room_agent_order {
    id: 主键id/bigint(20) unsigned
    agent_account_id: 代理人账号id/bigint(20)
    landlord_account_id: 房东账号id/bigint(20)
    room_source_id: 房源id/bigint(20)
    create_time: 记录创建时间/timestamp
    order_time: 签单时间/date
    tip_money: 佣金额度/元/int(11)
    settlement_form: 结算形式/一单一结，月结/tinyint(11)
}

entity " landlord_room_rent_record 房源出租记录表" as landlord_room_rent_record {
    id: 主键id/bigint(20) unsigned
    landlord_account_id: 房东账号id/bigint(20)
    room_source_id: 房源id/bigint(20)
    agent_account_id: 代理人账号id/bigint(20)
    room_source_index: 房源房屋序号索引/int(11)
    user_id: 用户id/bigint(20)
    contract_id: 合同ID/bigint(20)
    rent_start_time: 出租开始时间/date
    rent_end_time: 出租结束时间/date
    real_end_time: 出租实际结束时间/date
    create_time: 记录创建时间/timestamp
    update_time: 记录修改时间/timestamp
}



landlord_room_source ||--o{ real_room_source
account ||--o{ attract_investment


@enduml