spring:
  gateway:
    discovery:
      locator:
        enabled: false # ???????????????false ????
        lowerCaseServiceId: false # ????????????????????false?????
    httpclient: #http????
      pool:
        max-connections: 5000 #?????
        #       max-life-time: 45000 #??????
        acquire-timeout: 15000 #????
        max-idle-time: 10000 #??????