@startuml

participant  应用api层 as  facade
participant  领域层 as  domain
participant  基础设施层 as  infrast
group 系统上下文调用流程
facade --> domain: 1.查询系统信息是否已注册\nSystemFacade.registSystem invoke SystemModuleRepository.getSystemByCode
domain --> infrast:2.查询系统信息\n SystemModuleRepository.getSystemByCode invoke SystemMapper.getByCode

facade --> domain: 3.注册系统\nSystemFacade.registSystem invoke SystemModuleRepository.saveSystem
domain --> infrast:4.持久化系统数据\n SystemModuleRepository.saveSystem invoke SystemMapper.insert

domain --> infrast:5.发送mq\n SystemModuleRepository.saveSystem invoke SystemMqProducer.systemChange

end

@enduml