@startuml

participant  应用api层 as  facade
participant  领域层 as  domain
participant  基础设施层 as  infrast
group 系统上下文调用流程
facade --> domain: 1.根据权限code查询权限信息\nAuthorityFacade.getByCode invoke AuthorityFactory.buildAuthorityByCode
domain --> domain:2.查询权限详情\n AuthorityFactory.buildAuthorityByCode invoke AuthorityRepository.getByCode
domain --> infrast:3.查询权限详情\n AuthorityRepository.getByCode invoke AuthorityMapper.getByCode
domain --> infrast:4.查询系统权限详情\n AuthorityRepository.getByCode invoke SystemAuthorityMapper.getByCode
domain --> infrast:5.查询行政权限详情\n AuthorityRepository.getByCode invoke AdminAuthorityMapper.getByCode

end

@enduml