@startuml

participant  应用api层 as  app
participant  领域层 as  domain
participant  基础设施层 as  infrast
group 系统上下文调用流程
app_http --> domain: 1.给某角色授权\nAuthorityOperationController.saveAuthority invoke AuthorityRepository.buildAuthority
domain --> infrast:2.准备保存角色授权数据\n AuthorityRepository.buildAuthority invoke AuthorityMapper.insert
domain --> infrast:3.保存系统权限数据\n AuthorityRepository.buildAuthority invoke SystemAuthorityMapper.insert
domain --> infrast:4.保存行政权限详情\n AuthorityRepository.buildAuthority invoke AdminAuthorityMapper.insert
domain --> infrast:5.保存数据权限详情\n AuthorityRepository.buildAuthority invoke DataAuthorityMapper.insert
app_http --> infrast:6.发送授权消息\n AuthorityFacade.saveAuthority invoke AuthorityMqProducer.authorityCreate

end

@enduml