@startuml

participant  应用facade层 as  facade
participant  应用http层 as  http
participant  领域层 as  domain
participant  基础设施层 as  infrast

group 创建角色
app_http --> domain: 1.创建角色\n RoleController.createRole invoke UserRoleRepository.saveRole
domain --> infrast:2.持久化角色\n UserRoleRepository.saveRole invoke RoleMapper.insert
end

group
http --> domain: 1.禁用角色\n RoleController.disable invoke UserRoleRepository.getByRoleCode
domain --> infrast:2.持久化变更\n RoleController.disable invoke UserRoleRepository.updateRole
domain --> infrast:2.持久化变更\n UserRoleRepository.updateRole invoke RoleMapper.update
end


group
http --> domain: 1.分页获取角色 \n RoleQueryController.getPageList invoke UserRoleRepository.getPageList
domain --> infrast:2.持久化变更\n UserRoleRepository.getPageList invoke RoleMapper.getPageList(PageBO)
end

@enduml