@startuml

participant  应用facade层 as  facade
participant  应用http层 as  http
participant  领域层 as  domain
participant  基础设施层 as  infrast

group 导入数据字段内容
http --> domain: 3.注册系统\n DataColumnController.importDataColumnList invoke DataColumnGataWay.saveBatchDataColumn
domain --> infrast:4.持久化系统数据\n DataColumnGataWay.saveBatchDataColumn invoke DataColumnConfigMapper.insertBatch(List<DataColumnConfigDO>)
end


group 分页查询
http --> domain: 3.注册系统\n DataColumnController.getPageList invoke DataColumnGataWay.getPageList
domain --> infrast:4.持久化系统数据\n DataColumnGataWay.getPageList invoke DataColumnConfigMapper.getPageList(PageBO)
end

group
http --> domain: 3.注册系统\n DataColumnController.getListByBusDataBase invoke DataColumnGataWay.getByDBCode
domain --> infrast:4.持久化系统数据\n DataColumnGataWay.getByDBCode invoke DataColumnConfigMapper.getByDBCode(String busDataBase)
end


@enduml